{
 "title": "MOHSEN - S1 (ALPHA)",
 "tags": [ "alpha" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": "icinga2.*" }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "icinga2.*.services.load.load.perfdata.load1.value"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(icinga2.$host.services.check_mem.dummy.perfdata.MUSED.value, 'Memory Used')"
    },
    {
     "target": "alias(icinga2.$host.services.check_mem.dummy.perfdata.MBUFFER.value, 'Memory Buffer')"
    },
    {
     "target": "alias(icinga2.$host.services.check_mem.dummy.perfdata.MCACHE.value, 'Memory Cache')"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(icinga2.$host.services.check_mem.dummy.perfdata.MTOTAL.value, 'SERVER')"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "alias(icinga2.$host.services.swap.dummy.perfdata.swap.value, 'SERVER')"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(icinga2.$host.services.load.dummy.perfdata.load1.value, 'Load 1m')"
    },
    {
     "target": "alias(icinga2.$host.services.load.dummy.perfdata.load5.value, 'Load 5m')"
    },
    {
     "target": "alias(icinga2.$host.services.load.dummy.perfdata.load15.value, 'Load 15m')"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "icinga2.$host.services.procs.dummy.perfdata.procs.value"
    }
   ]
  },
  {
   "title": "Ping4",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "aliasSub(aliasByNode(icinga2.$host.services.ping4.dummy.perfdata.rta.value, 6), '_', '/')"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(aliasByNode(icinga2.$host.services.disk*.dummy.perfdata.*.value, 6), '_', '/')"
    }
   ]
  }
 ]
}